name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Install deps
        run:  uv sync --frozen --no-install-project
      - name: Lint
        run: uv run ruff check --fix
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup DB
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '16-alpine'
          postgresql user: 'postgres'
          postgresql password: ${{ secrets.DB_PASS }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
      - name: Install deps
        run:  uv sync --frozen --no-install-project
      - name: Test
        run: uv run pytest -v
